name = "tiktok-blog"
compatibility_date = "2024-09-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "tiktok_blog_db"
database_id = "07a6f7d1-97b8-4ccf-94af-94d3cbb7a6a0"
